### ISSUE TITLE
Question: blacklist user/repo

### ISSUE THREAD

**Issue by majormoses** [caarlos0/org-stats#9]
How can you blacklist a user but not a repo with the same name as a user. For example in the sensu plugins org we have a repo called: https://github.com/sensu-plugins/sensu-plugin we also have a user sharing the same name: https://github.com/sensu-plugin is it currently possible to filter out the user but not the repo or would this need an enhancement?

**Comment by caarlos0** [comment]
hmmm no, right now only repos can be blacklisted... PRs appreciated though :)

**Comment by majormoses** [comment]
I am no go programmer so I am not sure I can enhance that but one of these weekends I can take a crack at it. Also Based on the help message I think we need to change the verbiage as it implies both are possible that I can probably create a pr for it sooner if you agree.
```
$ org-stats --help | grep blacklist
   --blacklist value, -b value  Blacklist repos and/or users
```

**Comment by caarlos0** [comment]
actually, both users and repos are supported... so this is already fixed :)

**Comment by caarlos0** [comment]
hmmm, yeah, if you blacklist one it will blacklist both :/

maybe that's an improvement we can do...

**Comment by caarlos0** [comment]
on the next release you will be able to `--blacklist user:foo --blacklist repo:bar --blacklist something`.
